Repository tangem/tangem-app-ios, pull requests merged in 2023-12, with the labels that each got.

#2475 IOS-5257: Fix missed ru localization in tx history
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
Labels: release

#2478 iOS-5295: Main screen token list corner radius
  Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
  Tangem/UIComponents/TokenItemView/TokenItemView.swift
Labels: release

#2484 IOS-5280 Reorder buttons
  Tangem/Common/TokenActions/TokenActionListBuilder.swift
Labels: release

#2495 IOS-5264 express pending tx bottom sheet
  Tangem/App/Services/Express/PendingExpressTransactionsManager.swift
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
  Tangem/App/Services/NotificationManagers/NotificationButtonActionType.swift
  Tangem/App/Utilities/Express/PendingExpressTransactionsConverter.swift
  Tangem/Common/Extensions/WeakifyFuncion.swift
  Tangem/Common/UI/Modifiers/RoundedBackgroundModifier.swift
  Tangem/Modules/TokenDetails/ExpressBottomSheet/PendingExpressTransactionStatusRow.swift
  Tangem/Modules/TokenDetails/ExpressBottomSheet/PendingExpressTxStatusBottomSheetView.swift
  Tangem/Modules/TokenDetails/ExpressBottomSheet/PendingExpressTxStatusBottomSheetViewModel.swift
  Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
  Tangem/Modules/TokenDetails/TokenDetailsCoordinatorView.swift
  Tangem/Modules/TokenDetails/TokenDetailsRoutable.swift
  Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
  Tangem/Resources/Assets/Assets.xcassets/approx.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/approx.imageset/approx.pdf
  Tangem/Resources/Assets/Assets.xcassets/checkmark20.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/checkmark20.imageset/checkmark20.pdf
  Tangem/Resources/Assets/Assets.xcassets/circleOutline20.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/circleOutline20.imageset/circleOutline20.pdf
  Tangem/Resources/Assets/Assets.xcassets/cross20.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/cross20.imageset/cross20.pdf
  Tangem/Resources/Assets/Assets.xcassets/exclamationMark20.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/exclamationMark20.imageset/exclamationMark20.pdf
  Tangem/Resources/Assets/Assets.xcassets/verticalLine.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/verticalLine.imageset/verticalLine.pdf
  Tangem/UIComponents/NotificationView/Modifiers/NotificationTransitionModifier.swift
  TangemApp.xcodeproj/project.pbxproj
Labels: release

#2489 iOS-5296: Fix context menu previews clipping on iOS 17.0 and above
  Tangem/Common/UI/Modifiers/ContinuousCornerRadius.swift
  Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
  Tangem/UIComponents/TokenItemView/TokenItemView.swift
  Tangem/UIComponents/TokenSectionView/TokenSectionView.swift
Labels: release

#2503 IOS-5321: [Express] Font/Text checking
  Tangem/Common/UI/AmountSummary/AmountSummaryView.swift
  Tangem/Common/UI/AmountSummary/AmountSummaryViewData.swift
  Tangem/Common/UI/ReceiveCurrencyView/ReceiveCurrencyView.swift
  Tangem/Common/UI/SendCurrencyView/SendCurrencyView.swift
  Tangem/Modules/ExpressSuccessSent/ExpressSuccessSentViewModel.swift
Labels: release

#2501 IOS-5332 fix doubling assets request
  Tangem/App/Services/UserTokenListManager/CommonUserTokenListManager.swift
  Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
Labels: release

#2508 IOS-5235 [Express] Analitycs
  Tangem/App/Factories/ExpressModulesFactory/CommonExpressModulesFactory.swift
  Tangem/App/Models/Express/SentExpressTransactionData.swift
  Tangem/App/Services/Analytics/Analytics+Event.swift
  Tangem/App/Services/Analytics/Analytics+ParameterKey.swift
  Tangem/App/Services/ExpressInteractor/ExpressInteractor.swift
  Tangem/Modules/ExpressProvidersBottomSheet/ExpressProvidersBottomSheetViewModel.swift
  Tangem/Modules/ExpressSuccessSent/ExpressSuccessSentViewModel.swift
  Tangem/Modules/ExpressTokensList/ExpressTokensListView.swift
  Tangem/Modules/ExpressTokensList/ExpressTokensListViewModel.swift
  Tangem/Modules/ExpressView/ExpressCoordinator.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
Labels: release

#2509 IOS-5334 [Express] Update work with errors 2
  Tangem/App/Services/ExpressProviderFormatter/ExpressProviderFormatter.swift
  TangemSwapping/Manager/ExpressManager/CommonExpressManager.swift
  TangemSwapping/Manager/ExpressManager/ExpectedQuote.swift
  TangemSwapping/Services/ExpressAPIService/CommonExpressAPIService.swift
  TangemSwapping/Services/ExpressAPIService/Types/ExpressAPIError.swift
Labels: release

#2511 IOS-5339 [Express] Remove unnecessary /pairs request from ExpressTokensListViewModel
  Tangem/Modules/ExpressTokensList/ExpressTokensListViewModel.swift
Labels: release

#2518 IOS-5340 [Express] Update selected quote after each update
  Tangem/Modules/ExpressProvidersBottomSheet/ExpressProvidersBottomSheetViewModel.swift
  TangemSwapping/Manager/ExpressManager/CommonExpressManager.swift
Labels: release

#2520 IOS-5348: Custom codable for iOS 14
  Tangem/App/Services/ExpressPendingTransactionRepository/CommonExpressPendingTransactionRepository.swift
  Tangem/App/Services/ExpressPendingTransactionRepository/ExpressPendingTransactionRecord.swift
  Tangem/Common/Extensions/Decimal+.swift
  Tangem/Modules/TokenDetails/ExpressBottomSheet/PendingExpressTxStatusBottomSheetView.swift
Labels: release

#2521 IOS-5369: Fix wrong currency symbol in permission notif
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
Labels: release

#2462 Ios 5109 chart manage tokens
  Tangem/App/Models/Quotes/Quote.swift
  Tangem/App/Models/Quotes/QuotesDTO.swift
  Tangem/App/Models/Quotes/QuotesMapper.swift
  Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
  Tangem/App/Services/TokenQuotesRepository/TokenQuote.swift
  Tangem/Modules/ManageTokens/TokenList/ManageTokensItemViewModel.swift
  Tangem/Preview Content/Fakes/FakeTokenQuotesRepository.swift
  Tangem/Preview Content/Mocks/TokenQuotesRepositoryMock.swift
Labels: WIP

#2524 IOS-5365 [Express] Add `isCustom` checking
  Tangem/App/Services/ExpressDestinationService/CommonExpressDestinationService.swift
  Tangem/Modules/ExpressTokensList/ExpressTokensListViewModel.swift
  Tangem/Modules/SingleTokenBase/SingleTokenBaseViewModel.swift
Labels: release

#2525 IOS-5335 [Express] Update CommonExpressManager checkRestriction's order
  TangemSwapping/Manager/ExpressManager/CommonExpressManager.swift
Labels: release

#2527 IOS-5344: [Express] Full refresh doesn't work
  Tangem/App/Services/ExpressInteractor/ExpressInteractor.swift
Labels: release

#2535 IOS-5360: Remove not supported Infura NEAR RPC endpoint
  Podfile
  Podfile.lock
Labels: release

#2556 IOS-5427: Skip creating task for empty pending tx list
  Tangem/App/Services/Express/PendingExpressTransactionsManager.swift
Labels: release

#2552 IOS-5316 Fixed the swapping condition
  Tangem/App/Services/SwapAvailabilityManager/SwapPairService.swift
Labels: release

#2554 IOS-5417: [Express] DEX fee
  TangemSwapping/Manager/ExpressProviderManager/Implementations/DEXExpressProviderManager.swift
Labels: release

#2557 IOS-5426 [Express] Save the loaded quotes for next errors
  TangemSwapping/Manager/ExpressProviderManager/Implementations/CEXExpressProviderManager.swift
  TangemSwapping/Manager/ExpressProviderManager/Implementations/DEXExpressProviderManager.swift
Labels: release

#2558 IOS-5428 [Express] Percent from the best rate
  Tangem/Modules/ExpressProvidersBottomSheet/ExpressProvidersBottomSheetViewModel.swift
Labels: release

#2559 IOS-5388 [Express] Bubble's paddings
  Tangem/Common/UI/ReceiveCurrencyView/ReceiveCurrencyView.swift
  Tangem/Common/UI/SendCurrencyView/SendCurrencyView.swift
Labels: release

#2548 IOS-5324 [Express] Move on UIKit sheet presentation
  Tangem/App/Navigation/SheetModifier.swift
  Tangem/Modules/ExpressView/ExpressCoordinator.swift
  Tangem/Modules/ExpressView/ExpressCoordinatorView.swift
  Tangem/Modules/ExpressView/ExpressView.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
  Tangem/Modules/Main/MainCoordinatorView.swift
  Tangem/Modules/TokenDetails/TokenDetailsCoordinatorView.swift
  TangemApp.xcodeproj/project.pbxproj
Labels: release

#2555 IOS-5420 [Express] Add `isSwapButtonDisabled`
  Tangem/App/Factories/ExpressModulesFactory/CommonExpressModulesFactory.swift
  Tangem/App/Services/ExpressDestinationService/CommonExpressDestinationService.swift
  Tangem/App/Services/ExpressInteractor/ExpressInteractor.swift
  Tangem/App/Services/ExpressRepository/CommonExpressRepository.swift
  Tangem/Modules/ExpressTokensList/ExpressTokensListViewModel.swift
  Tangem/Modules/ExpressView/ExpressView.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
  TangemSwapping/Interfaces/ExpressRepository.swift
Labels: release

#2560 [Express] IOS-5431: Validate that user wallet can swap context menu
  Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
Labels: release

#2561 IOS-5440: [Express] "/Pairs" request logic
  Tangem/App/Factories/ExpressModulesFactory/CommonExpressModulesFactory.swift
  Tangem/App/Services/ExpressDestinationService/CommonExpressDestinationService.swift
  Tangem/App/Services/ExpressDestinationService/ExpressDestinationService.swift
  Tangem/App/Services/ExpressInteractor/ExpressInteractor.swift
  Tangem/Modules/ExpressProvidersBottomSheet/ExpressProvidersBottomSheetViewModel.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
Labels: release

#2570 IOS-5433: Request all tokens when adding new one
  Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
Labels: release

#2563 IOS-5425 [Express] Update CEX Quotes
  TangemSwapping/Manager/ExpressProviderManager/Implementations/CEXExpressProviderManager.swift
  TangemSwapping/Models/Express/ExpressQuote.swift
  TangemSwapping/Services/ExpressAPIProvider/CommonExpressAPIProvider.swift
Labels: release

#2565 IOS-5443 Updated promotion banner logic
  Tangem/App/Services/Common/AppSettings.swift
  Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
  Tangem/Common/Storage/StorageType.swift
Labels: release

#2567 IOS-5441: [Express] Fix for updating exchangeable state
  Tangem/App/Services/SwapAvailabilityManager/CommonSwapAvailabilityManager.swift
  Tangem/App/ViewModels/WalletModel/WalletModel.swift
  TangemApp.xcodeproj/project.pbxproj
  TangemSwapping/Models/Express/ExpressAsset.swift
  TangemSwapping/Services/ExpressAPIProvider/CommonExpressAPIProvider.swift
  TangemSwapping/Services/ExpressAPIProvider/ExpressAPIProvider.swift
Labels: release

#2569 IOS-5316 Getting only the relevant pairs of swap
  Tangem/App/Services/SwapAvailabilityManager/SwapPairService.swift
Labels: release

#2572 IOS-5402 [Express] Add text to providers selector
  Tangem/App/Factories/ExpressModulesFactory/CommonExpressModulesFactory.swift
  Tangem/App/Factories/ExpressModulesFactory/ExpressModulesFactory.swift
  Tangem/Common/UI/ProviderRowView/ProviderRowView.swift
  Tangem/Common/UI/ReceiveCurrencyView/ReceiveCurrencyView.swift
  Tangem/Modules/ExpressProvidersBottomSheet/ExpressProvidersBottomSheetRoutable.swift
  Tangem/Modules/ExpressProvidersSelectorView/ExpressProvidersSelectorRoutable.swift
  Tangem/Modules/ExpressProvidersSelectorView/ExpressProvidersSelectorView.swift
  Tangem/Modules/ExpressProvidersSelectorView/ExpressProvidersSelectorViewModel.swift
  Tangem/Modules/ExpressSuccessSent/ExpressSuccessSentViewModel.swift
  Tangem/Modules/ExpressView/ExpressCoordinator.swift
  Tangem/Modules/ExpressView/ExpressCoordinatorView.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
  Tangem/Modules/LegacySend/LegacySendView.swift
  Tangem/Modules/SwappingApprove/SwappingApproveViewModel.swift
  Tangem/Resources/Assets/Assets.xcassets/expressMoreProvidersIcon.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/expressMoreProvidersIcon.imageset/expressMoreProvidersIcon.pdf
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/it.lproj/Localizable.strings
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
  TangemApp.xcodeproj/project.pbxproj
  TangemSwapping/Helpers/Sequence+Async.swift
Labels: release

#2575 IOS-5449 [Express] Add policy to extension Analytics
  Tangem/App/Services/Analytics/Analytics+ParameterValue.swift
  Tangem/App/Services/ExpressInteractor/ExpressInteractor.swift
  TangemSwapping/Manager/ExpressManager/ExpressManagerState.swift
  TangemSwapping/Manager/ExpressProviderManager/Implementations/DEXExpressProviderManager.swift
Labels: release

#2577 IOS-5328 [Express] Update CommonExpressDestinationService
  Tangem/App/Services/ExpressDestinationService/CommonExpressDestinationService.swift
  Tangem/App/Services/ExpressInteractor/ExpressInteractor.swift
Labels: release

#2581 IOS-5457: Wrong anal events names
  Tangem/App/Services/Analytics/Analytics+Event.swift
Labels: release

#2580 IOS-5454: Fix appear anims for notifs TokenDetails
  Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
  Tangem/Modules/TokenDetails/TokenDetailsView.swift
  Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
Labels: release

#2576 IOS-5430: [Express] Legal texts
  Tangem/App/Services/ExpressPendingTransactionRepository/ExpressPendingTransactionRecord.swift
  Tangem/App/Services/ExpressProviderFormatter/ExpressProviderFormatter.swift
  Tangem/Common/UI/AttributedTextView.swift
  Tangem/Modules/ExpressView/ExpressView.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
  Tangem/Modules/TokenDetails/ExpressBottomSheet/PendingExpressTxStatusBottomSheetView.swift
  TangemSwapping/Models/Express/ExpressCurrency.swift
  TangemSwapping/Models/Express/ExpressProvider.swift
  TangemSwapping/Services/ExpressAPIMapper/ExpressAPIMapper.swift
  TangemSwapping/Services/ExpressAPIProvider/CommonExpressAPIProvider.swift
  TangemSwapping/Services/ExpressAPIService/Types/ExpressDTO.swift
Labels: release

#2579 IOS-5458: [Express] percent formula
  Tangem/Modules/ExpressProvidersSelectorView/ExpressProvidersSelectorViewModel.swift
  TangemSwapping/Models/Express/ExpressAvailableProvider.swift
Labels: release

#2583 IOS-5387 [Express] UI review
  Tangem/Common/UI/ProviderRowView/ProviderRowView.swift
  Tangem/Common/UI/ReceiveCurrencyView/ReceiveCurrencyView.swift
  Tangem/Common/UI/SendCurrencyView/SendCurrencyView.swift
  Tangem/Modules/ExpressProvidersSelectorView/ExpressProvidersSelectorView.swift
Labels: release

#2582 IOS-5459: [Express] BestRate on main express view
  Tangem/Modules/ExpressView/ExpressViewModel.swift
Labels: release

#2585 IOS-5405 [Express] HighPriceImpact logic
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
  Tangem/Common/UI/ReceiveCurrencyView/ReceiveCurrencyView.swift
  Tangem/Common/UI/ReceiveCurrencyView/ReceiveCurrencyViewModel.swift
  Tangem/Common/Utilities/HighPriceImpactCalculator.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
Labels: release

#2588 IOS-5465 [Express] Update ExpressTransactionBuilder
  Tangem/App/Services/ExpressTransactionBuilder/CommonExpressTransactionBuilder.swift
Labels: release

#2589 IOS-5438 [Express] Fix-isAvailable-sort-Priority
  TangemSwapping/Manager/ExpressManager/CommonExpressManager.swift
  TangemSwapping/Models/Express/ExpressAvailableProvider.swift
Labels: release

#2590 IOS-5392 [Express] Update background colors
  Tangem/Common/UI/ReceiveCurrencyView/ReceiveCurrencyView.swift
  Tangem/Common/UI/SendCurrencyView/SendCurrencyView.swift
  Tangem/Modules/ExpressFeeBottomSheet/ExpressFeeBottomSheetView.swift
  Tangem/Modules/ExpressProvidersSelectorView/ExpressProvidersSelectorView.swift
  Tangem/Modules/ExpressSuccessSent/ExpressSuccessSentView.swift
  Tangem/Modules/ExpressSuccessSent/ExpressSuccessSentViewModel.swift
  Tangem/Modules/ExpressView/ExpressView.swift
  Tangem/Modules/SwappingApprove/SwappingApproveView.swift
Labels: release

#2593 IOS-5466: [Express] Update estimated fee BSDK tag
  Podfile
  Podfile.lock
  TangemSwapping/Manager/ExpressProviderManager/Implementations/DEXExpressProviderManager.swift
Labels: release

#2594 IOS-5404: [Express] Additional fee footnote text
  Tangem/Modules/ExpressView/ExpressView.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/it.lproj/Localizable.strings
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
Labels: release

#2595 IOS-5472 [Express] Add `txExtraId` a.k.a MEMO
  Tangem/App/Services/ExpressTransactionBuilder/CommonExpressTransactionBuilder.swift
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
  TangemSwapping/Models/Express/ExpressTransactionData.swift
  TangemSwapping/Services/ExpressAPIMapper/ExpressAPIMapper.swift
  TangemSwapping/Services/ExpressAPIService/Types/ExpressDTO.swift
Labels: release

#2597 IOS-5473 [Express] Update `estimatedFee` to generate address
  Podfile
  Podfile.lock
  Tangem/App/Services/ExpressFeeProvider/CommonExpressFeeProvider.swift
Labels: release

#2599 IOS-5391 [Express] Update ExpressTokensListView UI review
  Tangem/Modules/ExpressTokensList/ExpressTokensListView.swift
Labels: release

#2602 IOS-5481 [Express] Empty search view
  Tangem/Modules/ExpressTokensList/ExpressTokensListView.swift
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/it.lproj/Localizable.strings
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
Labels: release

#2605 IOS-5336 [Express] Add `insufficientFunds` instead of notification
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
  Tangem/Common/UI/SendCurrencyView/SendCurrencyView.swift
  Tangem/Common/UI/SendCurrencyView/SendCurrencyViewModel.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
Labels: release

#2612 IOS-5488 [Express] Update to BDSK to develop-414.8
  Podfile
  Podfile.lock
Labels: release

#2611 IOS-5434 [Express] Update destination service
  Tangem/App/Models/Express/PendingExpressTransactionStatus.swift
  Tangem/App/Services/Analytics/Analytics+ParameterValue.swift
  Tangem/App/Services/Express/AnalyticsTracker/CommonPendingExpressTransactionAnalyticsTracker.swift
  Tangem/App/Services/Express/PendingExpressTransactionsManager.swift
  Tangem/App/Services/ExpressDestinationService/CommonExpressDestinationService.swift
  Tangem/App/Services/ExpressInteractor/ExpressInteractor.swift
  Tangem/App/Services/ExpressPendingTransactionRepository/CommonExpressPendingTransactionRepository.swift
  Tangem/App/Services/ExpressPendingTransactionRepository/ExpressPendingTransactionRepository.swift
  Tangem/App/Utilities/Express/PendingExpressTransactionFactory.swift
  Tangem/App/Utilities/Express/PendingExpressTransactionsConverter.swift
Labels: release

#2620 IOS-5324 [Express] iOS17UIKitSheet -> iOS16UIKitSheet
  Tangem/App/Navigation/SheetModifier.swift
  Tangem/Modules/ExpressView/ExpressCoordinatorView.swift
  Tangem/Modules/Main/MainCoordinatorView.swift
  Tangem/Modules/TokenDetails/TokenDetailsCoordinatorView.swift
Labels: release

#2615 IOS-5511: App storage refactoring
  Tangem/App/Services/Common/AppSettings.swift
  Tangem/Common/Storage/AppStorageCompat.swift
  Tangem/Common/Storage/PropertyListObjectRepresentable.swift
  TangemApp.xcodeproj/project.pbxproj
Labels: blocked

#2621 IOS-5480 [Express] Max amount request strange stopped request
  Podfile
  Podfile.lock
  Tangem/App/Services/ExpressInteractor/ExpressInteractor.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
Labels: release

#2631 IOS-5526 [Express] Update when LegalText visible
  Tangem/Modules/ExpressView/ExpressViewModel.swift
Labels: release

#2626 IOS-5483: [Express] Cancelled status
  Tangem/App/Models/Express/PendingExpressTransactionStatus.swift
  Tangem/App/Services/Analytics/Analytics+ParameterValue.swift
  Tangem/App/Services/Express/AnalyticsTracker/CommonPendingExpressTransactionAnalyticsTracker.swift
  Tangem/App/Services/Express/PendingExpressTransactionsManager.swift
  Tangem/App/Services/ExpressPendingTransactionRepository/CommonExpressPendingTransactionRepository.swift
  Tangem/App/Utilities/Express/PendingExpressTransactionFactory.swift
  Tangem/App/Utilities/Express/PendingExpressTransactionsConverter.swift
  Tangem/Modules/TokenDetails/ExpressBottomSheet/PendingExpressTransactionStatusRow.swift
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/it.lproj/Localizable.strings
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
  TangemSwapping/Models/Express/ExpressTransactionStatus.swift
Labels: release

#2634 IOS-5530 [Express] Timer fixes
  Tangem/App/Services/ExpressInteractor/ExpressInteractor.swift
  Tangem/Common/UI/ReceiveCurrencyView/ReceiveCurrencyView.swift
  Tangem/Common/UI/SendCurrencyView/SendCurrencyView.swift
  Tangem/Modules/ExpressFeeBottomSheet/ExpressFeeBottomSheetViewModel.swift
  Tangem/Modules/ExpressSuccessSent/ExpressSuccessSentViewModel.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
  Tangem/Modules/SwappingApprove/SwappingApproveViewModel.swift
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/it.lproj/Localizable.strings
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
Labels: release

#2636 IOS-5532 [Express] Add `existentialDepositWarning`
  Tangem/App/Factories/ExpressModulesFactory/CommonExpressModulesFactory.swift
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
  Tangem/App/ViewModels/WalletModel/WalletModel.swift
Labels: release

#2637 IOS-5533 [Express] Update to token name in ExpressNotificationManager
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
Labels: release

#2638 IOS-5534 [Express] `Exchange` to `Swap`
  Tangem/Common/TokenActions/TokenActionType.swift
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/it.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
  Tangem/UIComponents/TokenItemMenuActions/TokenItemMenuActions.swift
Labels: release

#2639 IOS-5542 [Express] Update Colors
  Tangem/Resources/Assets/Colors.xcassets/Stroke/StrokePrimary.colorset/Contents.json
Labels: release

#2641 IOS-5487 [Express] Move all into scroll view
  Tangem/Modules/ExpressView/ExpressView.swift
Labels: release

#2651 IOS-5569 [Express] Use correct quotes
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
  Tangem/Modules/ExpressFeeBottomSheet/ExpressFeeBottomSheetViewModel.swift
  TangemSwapping/Manager/ExpressProviderManager/Implementations/DEXExpressProviderManager.swift
  TangemSwapping/Models/Express/DecodedTransactionDetails.swift
  TangemSwapping/Models/Express/ExpressQuote.swift
  TangemSwapping/Services/ExpressAPIMapper/ExpressAPIMapper.swift
  TangemSwapping/Services/ExpressAPIProvider/CommonExpressAPIProvider.swift
  TangemSwapping/Services/ExpressAPIService/Types/ExpressDTO.swift
Labels: release

#2659 IOS-5573 [Express] Update anal param
  Tangem/App/Services/ExpressInteractor/ExpressInteractor.swift
Labels: release
