Repository tangem/tangem-app-ios, pull requests merged in 2024-06, with the labels that each got.

#3373 IOS-7021 Filter recents
  Tangem/App/Services/TransactionHistoryRepository/CommonTransactionHistoryService.swift
  Tangem/App/Services/TransactionHistoryRepository/MultipleAddressTransactionHistoryService.swift
  Tangem/App/Utilities/TransactionHistoryMapper.swift
Labels: hotfix

#3378 IOS-7031 Update Beacon Chain message
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/it.lproj/Localizable.strings
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
Labels: hotfix

#3374 IOS-6807 Reset flow
  Podfile
  Podfile.lock
  Tangem/App/Email/EmailType.swift
  Tangem/App/Factories/CardEmailDataFactory.swift
  Tangem/App/Services/Analytics/Analytics+Event.swift
  Tangem/Common/TangemSdk/FactorySettingsResetting/FactorySettingsResetting.swift
  Tangem/Common/TangemSdk/FactorySettingsResetting/FactorySettingsResettingCardInteractor.swift
  Tangem/Modules/CardSettings/CardSettingsViewModel.swift
  Tangem/Modules/Main/MainViewModel.swift
  Tangem/Modules/Onboarding/Wallet/WalletOnboardingViewModel.swift
  Tangem/Modules/ResetToFactory/ResetToFactoryService.swift
  Tangem/Modules/ResetToFactory/ResetToFactoryView.swift
  Tangem/Modules/ResetToFactory/ResetToFactoryViewModel.swift
  Tangem/Modules/ResetToFactory/ResetToFactoryViewModelInput.swift
  Tangem/Modules/ScanCardSettings/ScanCardSettingsViewModel.swift
  Tangem/Preview Content/Mocks/Card/FactorySettingsResettingMock.swift
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/it.lproj/Localizable.strings
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
  TangemApp.xcodeproj/project.pbxproj
Labels: release

#3387 IOS-6966 ton tokens
  Podfile
  Podfile.lock
  TangemApp.xcodeproj/project.pbxproj
  TangemApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: blocked

#3394 IOS-7033 🍒 Custom-ADA-token
  Tangem/Modules/LegacyTokenList/AddCustomToken/LegacyAddCustomTokenViewModel.swift
  Tangem/Modules/ManageTokens/AddCustomToken/AddCustomTokenViewModel.swift
Labels: release

#3395 IOS-7037 🍒 Dust notification message
  Tangem/App/Services/NotificationManagers/BlockchainSDKNotifications/ValidationErrorEvent.swift
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
Labels: release

#3397 Ios 6966 ton tokens
  Podfile
  Podfile.lock
  TangemApp.xcodeproj/project.pbxproj
  TangemApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: release

#3393 IOS-7096 [Express] Update CommonExpressFeeProvider / increase gas limit
  Tangem/App/Services/ExpressFeeProvider/CommonExpressFeeProvider.swift
Labels: release

#3401 IOS-7096 🍒 [Express] Gas limit increase
  Tangem/App/Services/ExpressFeeProvider/CommonExpressFeeProvider.swift
Labels: release

#3398 IOS-7059 Add `Buy Tangem Wallet` to `Details`
  Tangem/Modules/Details/DetailsCoordinator.swift
  Tangem/Modules/Details/DetailsRoutable.swift
  Tangem/Modules/Details/DetailsView.swift
  Tangem/Modules/Details/DetailsViewModel.swift
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/it.lproj/Localizable.strings
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
Labels: release

#3410 IOS-7110: Update BSDK to `develop-548.19`
  Podfile
  Podfile.lock
Labels: release

#3406 Ios 6966 ton tokens app
  Podfile
  Podfile.lock
  TangemApp.xcodeproj/project.pbxproj
  TangemApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: release

#3415 IOS-7010: Fix broken ERC20 contract calls (to release)
  Podfile
  Podfile.lock
  Tangem/App/Models/Config/SupportedBlockchains.swift
  Tangem/App/Services/WalletConnect/Utilities/WalletConnectEthTransactionBuilder.swift
  Tangem/Modules/Send/Fee/CustomFeeService/CustomEvmFeeService.swift
Labels: release

#3418 IOS-7046: New cobrand cards support cherry-pick
  Tangem/App/Models/UserWallet/Implementations/Wallet2Config.swift
  Tangem/Resources/Assets/Assets.xcassets/Cards/babyDogeDouble.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/babyDogeDouble.imageset/Property 1=BBD2.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/babyDogeTriple.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/babyDogeTriple.imageset/Property 1=BBD3.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/coinMetricaDouble.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/coinMetricaDouble.imageset/Property 1=Metrika2.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/coinMetricaTriple.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/coinMetricaTriple.imageset/Property 1=Metrika3.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/cryptosethDouble.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/cryptosethDouble.imageset/Property 1=CryptoSeth2.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/cryptosethTriple.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/cryptosethTriple.imageset/Property 1=CryptoSeth3.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/kishuDouble.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/kishuDouble.imageset/Property 1=Kishu Inu2.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/kishuTriple.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/kishuTriple.imageset/Property 1=Kishu Inu3.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/redPandaDouble.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/redPandaDouble.imageset/Property 1=RPM2.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/redPandaTriple.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/redPandaTriple.imageset/Property 1=RPM3.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/tgDouble.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/tgDouble.imageset/Property 1=COQ2.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/tgTriple.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/tgTriple.imageset/Property 1=COQ3.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/voltInuDouble.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/voltInuDouble.imageset/Property 1=Volt Inu2.pdf
  Tangem/Resources/Assets/Assets.xcassets/Cards/voltInuTriple.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/Cards/voltInuTriple.imageset/Property 1=Volt Inu3.pdf
Labels: release

#3422 IOS-7121 ton explorer link 5.11
  Podfile
  Podfile.lock
Labels: release

#3416 IOS-7115: Fix wallet models threading issues
  Tangem/App/Services/APIListProvider/CommonAPIListProvider.swift
Labels: release

#3423 IOS-7121 ton explorer link 5.12
  Podfile
  Podfile.lock
Labels: release

#3435 🍒 IOS-7024: Add platform header to api calls
  Tangem/App/Services/TangemApiService/TangemApiTarget.swift
Labels: bug, release

#3437 🍒 IOS-7025: Add APIURLValidator
  Tangem/App/Services/APIListProvider/APIListUtils.swift
  Tangem/App/Services/APIListProvider/APIURLValidator.swift
  TangemApp.xcodeproj/project.pbxproj
  TangemTests/APIURLValidatorTests.swift
Labels: bug, release

#3439 IOS-6995 to release
  Tangem/App/Services/ExpressInteractor/ExpressInteractor.swift
  Tangem/App/Services/NotificationManagers/BlockchainSDKNotifications/ValidationErrorContext.swift
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
  Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
  Tangem/Modules/Send/SendNotifications/SendNotificationManager.swift
  TangemApp.xcodeproj/project.pbxproj
Labels: WIP

#3440 IOS-7149: Substrate CheckMetadataHash extension support
  Podfile
  Podfile.lock
Labels: release

#3441 IOS-7144: Show alert for failed asset assoc tx
  Tangem/Modules/SingleTokenBase/SingleTokenAlertBuilder.swift
  Tangem/Modules/SingleTokenBase/SingleTokenBaseViewModel.swift
Labels: release

#3443 IOS-7144: Show alert for failed asset assoc tx (to release)
  Tangem/Modules/SingleTokenBase/SingleTokenAlertBuilder.swift
  Tangem/Modules/SingleTokenBase/SingleTokenBaseViewModel.swift
Labels: release

#3442 IOS-7141: Hedera token contract addresses normalization
  Podfile
  Podfile.lock
  Tangem/App/Utilities/CustomTokenContractAddressConverter.swift
  Tangem/App/Utilities/HighPriceImpactCalculator.swift
  Tangem/App/Utilities/LocalizationIconParser.swift
  Tangem/App/Utilities/TangemBlogUrlBuilder.swift
  Tangem/App/Utilities/TokenInteractionAvailabilityProvider.swift
  Tangem/Modules/LegacyTokenList/AddCustomToken/LegacyAddCustomTokenViewModel.swift
  Tangem/Modules/ManageTokens/AddCustomToken/AddCustomTokenViewModel.swift
  TangemApp.xcodeproj/project.pbxproj
Labels: release

#3449 IOS-7141 to release (5.12)
  Podfile
  Podfile.lock
  Tangem/App/Utilities/CustomTokenContractAddressConverter.swift
  Tangem/App/Utilities/HighPriceImpactCalculator.swift
  Tangem/App/Utilities/LocalizationIconParser.swift
  Tangem/App/Utilities/TangemBlogUrlBuilder.swift
  Tangem/App/Utilities/TokenInteractionAvailabilityProvider.swift
  Tangem/Modules/LegacyTokenList/AddCustomToken/LegacyAddCustomTokenViewModel.swift
  Tangem/Modules/ManageTokens/AddCustomToken/AddCustomTokenViewModel.swift
  TangemApp.xcodeproj/project.pbxproj
Labels: release

#3459 IOS-7157: Add provider for substrate network runtime version (to release)
  Podfile
  Podfile.lock
Labels: release

#3456 IOS-6885: Existential deposit handling in Send
  Tangem/Modules/Send/SendModel.swift
Labels: release

#3464 IOS-6885: Fix existential deposit handling in Send (to release)
  Tangem/Modules/Send/SendModel.swift
Labels: release

#3465 IOS-7213 Add missing de ln
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
Labels: release
