Repository tangem/tangem-app-ios, pull requests merged in 2024-09, with the labels that each got.

#3764 IOS-7852 Fix tron tokens
  Podfile
  Podfile.lock
Labels: release

#3787 IOS-7873 Fix swap issues
  Tangem/App/Factories/ExpressModulesFactory/CommonExpressModulesFactory.swift
  Tangem/App/Services/Express/ExpressInteractor/ExpressInteractor.swift
  Tangem/Modules/ExpressApprove/ExpressApproveViewModel.swift
  Tangem/Modules/ExpressView/ExpressViewModel.swift
  Tangem/Modules/Send/SendTransactionDispatcher/SendTransactionDispatcher.swift
  Tangem/Preview Content/Mocks/Express/ExpressModulesFactoryMock.swift
Labels: release

#3747 IOS-7689 [Markets] make analytics events
  Tangem/App/Services/Analytics/Analytics+Event.swift
  Tangem/App/Services/Analytics/Analytics+ParameterValue.swift
  Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
  Tangem/Modules/Main/SingleWalletMainContent/SingleWalletMainContentViewModel.swift
  Tangem/Modules/Markets/Providers/MarketsListDataFilterProvider.swift
  Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/HistoryChart/MarketsHistoryChartViewModel.swift
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/Insights/MarketsTokenDetailsInsightsViewModel.swift
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/PricePerformance/MarketsTokenDetailsPricePerformanceViewModel.swift
  Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
  Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorViewModel.swift
  Tangem/Modules/Markets/UIComponents/MarketsRatingHeaderViewModel.swift
  Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
Labels: blocked

#3860 Kaspa fee estimation
  Podfile
  Podfile.lock
  Tangem/App/Models/Config/SupportedBlockchains.swift
  Tangem/Modules/Send/Fee/CustomFeeService/CustomKaspaFeeService.swift
  Tangem/Modules/Send/Fee/CustomFeeService/Kaspa/KaspaFeeCalculationModel.swift
  TangemApp.xcodeproj/project.pbxproj
Labels: release

#3867 IOS-7932 [Staking] Update text for `Cosmos` unstaking
  Tangem/Modules/Send/StakingNotifications/StakingNotificationEvent.swift
  Tangem/Modules/Send/StakingNotifications/StakingNotificationManager.swift
Labels: release

#3863 IOS-7978 [Staking] Locked status fixes
  Tangem/Modules/StakingDetails/Components/StakingDetailsStakeView/StakingDetailsStakeViewData.swift
  Tangem/Modules/StakingDetails/Components/StakingDetailsStakeView/StakingDetailsStakeViewDataBuilder.swift
  Tangem/Resources/Assets/Assets.xcassets/stakingLockIcon.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/stakingLockIcon.imageset/stakingLockIcon.pdf
  Tangem/Resources/Assets/Assets.xcassets/stakingUnlockingIcon.imageset/Contents.json
  Tangem/Resources/Assets/Assets.xcassets/stakingUnlockingIcon.imageset/stakingUnlockingIcon.pdf
  TangemStaking/Services/StakingPendingTransactionsRepository/CommonStakingPendingTransactionsRepository.swift
Labels: release

#3856 IOS-7909 [Staking] Tron integer logic
  Tangem/Modules/Send/Amount/Interactor/SendAmountInteractor.swift
  Tangem/Modules/Send/Amount/Interactor/SendAmountModifier.swift
  Tangem/Modules/Send/Amount/SendAmountView.swift
  Tangem/Modules/Send/Amount/SendAmountViewModel.swift
  Tangem/Modules/Send/Helpers/FeeIncludedCalculator/CommonFeeIncludedCalculator.swift
  Tangem/Modules/Send/Helpers/FeeIncludedCalculator/FeeIncludedCalculator.swift
  Tangem/Modules/Send/Helpers/FeeIncludedCalculator/StakingFeeIncludedCalculator.swift
  Tangem/Modules/Send/SendFactories/SendDependenciesBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Flows/SendFlowBaseBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Flows/StakingFlowBaseBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Steps/SendAmountStepBuilder.swift
  TangemApp.xcodeproj/project.pbxproj
Labels: release

#3887 IOS-7975 Update locale for search header markets
  Tangem/Modules/Main/MainBottomSheet/Header/MainBottomSheetHeaderInputView.swift
Labels: release

#3864 IOS-7674 [Staking / Send] Update `SendScreenDataCollector`
  Tangem/App/Email/DataCollectors.swift
  Tangem/App/Email/EmailType.swift
  Tangem/Modules/Send/Base/Interactor/SendBaseInputOutput.swift
  Tangem/Modules/Send/Base/Interactor/SendBaseInteractor.swift
  Tangem/Modules/Send/Base/SendViewModel.swift
  Tangem/Modules/Send/SendFactories/SendAlertBuilder/SendBaseDataBuilder.swift
  Tangem/Modules/Send/SendFactories/SendDependenciesBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Flows/SellFlowBaseBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Flows/SendFlowBaseBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Flows/StakingFlowBaseBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Flows/UnstakingFlowBaseBuilder.swift
  Tangem/Modules/Send/SendModel.swift
  Tangem/Modules/Send/StakingModel.swift
  Tangem/Modules/Send/UnstakingModel.swift
  TangemApp.xcodeproj/project.pbxproj
Labels: release

#3872 IOS-7963 [Staking] StakingDetailsView supports refreshable on iOS 15
  Tangem/Modules/StakingDetails/StakingDetailsView.swift
  Tangem/Modules/StakingDetails/StakingDetailsViewModel.swift
Labels: release

#3881 IOS-7990: [Markets] Fix navigation issues on iOS 18
  Tangem/Modules/App/AppCoordinator.swift
  Tangem/Modules/App/AppCoordinatorView.swift
  Tangem/Modules/Markets/Common/BaseMarketsViewModel.swift
  Tangem/Modules/Markets/TokenList/MarketsView.swift
  Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsView.swift
  Tangem/UIComponents/OverlayContentContainer/SwiftUI/Interface/OverlayContentContainer.swift
  Tangem/UIComponents/OverlayContentContainer/SwiftUI/OverlayContentContainer+Environment.swift
  Tangem/UIComponents/OverlayContentContainer/SwiftUI/OverlayContentContainerViewControllerAdapter.swift
  Tangem/UIComponents/OverlayContentContainer/UIKit/OverlayContentContainerViewController.swift
Labels: release

#3886 IOS-7977 [Staking] Cosmos block reward
  Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
  Tangem/App/Services/NotificationManagers/SingleTokenNotifications/TokenNotificationEvent.swift
  Tangem/Modules/Send/StakingNotifications/StakingNotificationEvent.swift
  Tangem/Modules/StakingDetails/StakingDetailsViewModel.swift
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/es.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/it.lproj/Localizable.strings
  Tangem/Resources/Localizations/ja.lproj/Localizable.strings
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
  Tangem/Resources/Localizations/uk-UA.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
  TangemStaking/Models/RewardScheduleType.swift
  TangemStaking/Services/StakeKitMapper/StakeKitMapper.swift
Labels: release

#3892 IOS-8007 update price change fields in quotes request
  Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
Labels: release

#3879 IOS-7945 Custom fee fileds
  Tangem/Common/Extensions/View+ConditionalModifiers.swift
  Tangem/Common/UI/SendDecimalNumberTextField/DecimalNumberTextField.swift
Labels: release

#3891 IOS-7995: [Markets] Search input and clear events update
  Tangem/Modules/Main/MainBottomSheet/Header/MainBottomSheetHeaderViewModel.swift
  Tangem/Modules/Main/MainBottomSheet/Header/MainBottomSheetHeaderViewModelDelegate.swift
  Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
Labels: release

#3904 IOS-8020: Fix BTC RU locale links layout issue
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/Links/MarketsTokenDetailsChipsContainer.swift
Labels: release

#3900 IOS-7997: [Markets] Disable unnecessary keyboard avoidance
  Tangem/Modules/App/AppCoordinatorView.swift
Labels: release

#3903 IOS-8013: Fix manage tokens loader and selection coloring
  Tangem/Modules/LegacyTokenList/ListDataLoader.swift
  Tangem/UIComponents/ManageTokensListView/ListItems/ManageTokensListItemView.swift
  Tangem/UIComponents/ManageTokensListView/ListItems/ManageTokensListItemViewModel.swift
Labels: release

#3902 IOS-8018 Fix tooltip UI animation
  Tangem/Modules/Main/MainCoordinator.swift
  Tangem/UIComponents/Tooltip/BasicTooltipView.swift
Labels: release

#3880 IOS-6563 [Markets] make markets hits tutorial
  Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilder.swift
  Tangem/Modules/Main/MainView.swift
  Tangem/Modules/Main/UIComponents/MainBottomSheetHintView.swift
  Tangem/UIComponents/CardsInfoPagerView/CardsInfoPagerBottomOverlayFactoryParams.swift
  Tangem/UIComponents/CardsInfoPagerView/CardsInfoPagerScrollState.swift
  Tangem/UIComponents/CardsInfoPagerView/CardsInfoPagerView.swift
  TangemApp.xcodeproj/project.pbxproj
Labels: release

#3907 IOS-7981 [Staking] Show text if staking catch network error
  Tangem/App/ViewModels/WalletModel/WalletModel.swift
  Tangem/Modules/Main/MultiWalletMainContent/Views/TokenList/DefaultTokenItemInfoProvider.swift
  Tangem/Modules/StakingDetails/StakingDetailsViewModel.swift
  Tangem/Modules/TokenDetails/TokenDetailsView.swift
  Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
  Tangem/Modules/TokenDetails/Views/ActiveStakingView.swift
  Tangem/Preview Content/Mocks/Staking/StakingManagerMock.swift
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/es.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/it.lproj/Localizable.strings
  Tangem/Resources/Localizations/ja.lproj/Localizable.strings
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
  Tangem/Resources/Localizations/uk-UA.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
  TangemStaking/Services/StakingManager/CommonStakingManager.swift
  TangemStaking/Services/StakingManager/StakingManager.swift
Labels: release

#3908 IOS-8022: Add minimum scale for picker item
  Tangem/UIComponents/SegmentPickerView/SegmentedPicker.swift
Labels: release

#3898 IOS-7966: [Markets] Bottom sheet overscroll and spring animations
  Tangem/Common/Extensions/UIKit/CGPoint+.swift
  Tangem/Modules/App/AppCoordinatorView.swift
  Tangem/Modules/Markets/Navigation/MarketsCoordinatorView.swift
  Tangem/UIComponents/OverlayContentContainer/UIKit/OverlayContentContainerProgress.swift
  Tangem/UIComponents/OverlayContentContainer/UIKit/OverlayContentContainerViewController.swift
  Tangem/UIComponents/OverlayContentContainer/UIKit/UIView+OverlayContentContainerProgress.swift
Labels: release

#3915 IOS-8031 Show l2 in portfolio
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemFactory.swift
Labels: release

#3912 IOS-8012 Fix UI comments for tokens selector
  Tangem/Modules/ManageTokens/CustomTokensRelated/AddCustomToken/AddCustomTokenCoordinator.swift
  Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokenNetworkSelectorCoordinator.swift
  Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkDataSource.swift
  Tangem/Modules/WalletSelector/WalletSelectorRoutable.swift
  Tangem/Modules/WalletSelector/WalletSelectorView.swift
  Tangem/Modules/WalletSelector/WalletSelectorViewModel.swift
  Tangem/UIComponents/WalletSelectorItemView/WalletSelectorItemView.swift
  TangemApp.xcodeproj/project.pbxproj
Labels: release

#3918 IOS-8028: [Markets] Subscribe My portfolio to wallets repository updates
  Tangem/Common/TangemSdk/CardScanner/MockedCardScanner.swift
  Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
  Tangem/Modules/Markets/Providers/MarketsWalletDataSource.swift
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
  Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorViewModel.swift
Labels: release

#3917 IOS-8033 Make correct height tooltips
  Tangem/Modules/Main/UIComponents/MainBottomSheetHintView.swift
  Tangem/UIComponents/Tooltip/BasicTooltipView.swift
Labels: release

#3920 IOS-8030: Add text scaling to token details title
  Tangem/Common/UI/Navigation/NavigationBar.swift
  Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsView.swift
  Tangem/Modules/Onboarding/Note/SingleCardOnboardingView.swift
  Tangem/Modules/Onboarding/Twins/TwinsOnboardingView.swift
  Tangem/Modules/Onboarding/Wallet/WalletOnboardingView.swift
Labels: release

#3919 IOS-8005: Main bottom sheet offscreen snapshots
  Tangem/Common/UI/ViewHierarchySnapshotting/ViewHierarchySnapshotting.swift
  Tangem/Common/UI/ViewHierarchySnapshotting/ViewHierarchySnapshottingContainerViewController.swift
  Tangem/Common/UI/ViewHierarchySnapshotting/ViewHierarchySnapshottingWeakifyAdapter.swift
  Tangem/Common/UI/ViewStateHandler.swift
  Tangem/Modules/App/AppCoordinatorView.swift
  Tangem/Modules/Auth/AuthView.swift
  Tangem/Modules/Main/MainBottomSheet/Other/MainBottomSheetUIManager.swift
  Tangem/Modules/Main/MainCoordinator.swift
  Tangem/Modules/Main/MainFooterView/MainBottomSheet/MainBottomSheetFooterView.swift
  Tangem/Modules/Main/MainFooterView/MainBottomSheet/MainBottomSheetFooterViewModel.swift
  Tangem/Modules/Main/MainView.swift
  Tangem/Modules/Main/MainViewModel.swift
  Tangem/Modules/Markets/TokenList/MarketsView.swift
  Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
  Tangem/Modules/Markets/TokenList/MarketsViewNavigationControllerConfigurator.swift
  Tangem/Modules/Welcome/WelcomeView.swift
Labels: release

#3925 IOS-8019: [Markets] Total -> Max supply
  Tangem/App/Models/Markets/MarketsTokenDetailsMetrics.swift
  Tangem/Common/AppConstants.swift
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/Metrics/MarketsTokenDetailsMetricsView.swift
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/Metrics/MarketsTokenDetailsMetricsViewModel.swift
  Tangem/Resources/Localizations/de.lproj/Localizable.strings
  Tangem/Resources/Localizations/en.lproj/Localizable.strings
  Tangem/Resources/Localizations/es.lproj/Localizable.strings
  Tangem/Resources/Localizations/fr.lproj/Localizable.strings
  Tangem/Resources/Localizations/ja.lproj/Localizable.strings
  Tangem/Resources/Localizations/ru.lproj/Localizable.strings
  Tangem/Resources/Localizations/uk-UA.lproj/Localizable.strings
  Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
Labels: release

#3926 IOS-8039 [Staking] Pending balances
  Tangem/App/Services/Staking/PendingActionMapper.swift
  Tangem/Modules/StakingDetails/Components/StakingDetailsStakeView/StakingDetailsStakeViewDataBuilder.swift
  TangemStaking/Models/StakingBalance.swift
  TangemStaking/Models/StakingBalanceType.swift
  TangemStaking/Services/StakingManager/CommonStakingManager.swift
  TangemStaking/Services/StakingPendingTransactionsRepository/CommonStakingPendingTransactionsRepository.swift
Labels: release

#3922 IOS-8042 [Staking] Add missing data
  Tangem/App/Services/Analytics/Analytics+ParameterValue.swift
  Tangem/App/Services/Analytics/CommonStakingAnalyticsLogger.swift
  Tangem/Modules/Send/Finish/SendFinishViewModel.swift
  Tangem/Modules/Send/SendFactories/SendDependenciesBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Flows/SellFlowBaseBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Flows/SendFlowBaseBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Flows/StakingFlowBaseBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Flows/UnstakingFlowBaseBuilder.swift
  Tangem/Modules/Send/SendFactories/StepBuilders/Steps/SendFinishStepBuilder.swift
  Tangem/Modules/Send/SendMainButtonType.swift
  TangemStaking/Services/StakingAPIService/StakeKitStakingAPIService.swift
  TangemStaking/Services/StakingAnalytics/StakingAnalyticsLogger.swift
Labels: release

#3929 IOS-8050: Hedera swap error
  Podfile
  Podfile.lock
Labels: release

#3930 IOS-8052 Make fix analytics events
  Tangem/App/Services/Analytics/Analytics+Event.swift
  Tangem/App/Services/ManageTokens/ManageTokensAdapter.swift
  Tangem/Modules/ManageTokens/ManageTokensCoordinator.swift
  Tangem/Modules/ManageTokens/ManageTokensView.swift
  Tangem/Modules/Onboarding/AddTokens/OnboardingAddTokensView.swift
  Tangem/Modules/Onboarding/AddTokens/OnboardingAddTokensViewModel.swift
  Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
  Tangem/Modules/UserWalletSettings/UserWalletSettingsViewModel.swift
Labels: release

#3933 IOS-8024 mini chart crash
  Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
Labels: release

#3931 IOS-8053 Fix analytics events
  Tangem/App/Models/Markets/MarketsPriceIntervalType.swift
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/HistoryChart/MarketsHistoryChartViewModel.swift
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/Insights/MarketsTokenDetailsInsightsViewModel.swift
  Tangem/Modules/Markets/TokenMarketsDetails/Subviews/PricePerformance/MarketsTokenDetailsPricePerformanceViewModel.swift
  Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
  Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorViewModel.swift
Labels: release

#3937 IOS-8043 [Staking] Skip the skipped
  Tangem/Preview Content/Mocks/Staking/StakingTransactionInfo+Mock.swift
  TangemApp.xcodeproj/project.pbxproj
  TangemStaking/Models/ActionTransaction.swift
  TangemStaking/Models/StakingTransactionInfo.swift
  TangemStaking/Models/TransactionStatus.swift
  TangemStaking/Services/StakeKitMapper/StakeKitMapper.swift
  TangemStaking/Services/StakingManager/CommonStakingManager.swift
Labels: release

#3936 IOS-8059 update analytics custom tokens
  Tangem/App/Services/Analytics/Analytics+Event.swift
  Tangem/Modules/LegacyTokenList/AddCustomToken/LegacyAddCustomTokenViewModel.swift
  Tangem/Modules/ManageTokens/CustomTokensRelated/AddCustomToken/AddCustomTokenCoordinator.swift
  Tangem/Modules/ManageTokens/CustomTokensRelated/AddCustomToken/AddCustomTokenView.swift
  Tangem/Modules/ManageTokens/CustomTokensRelated/AddCustomToken/AddCustomTokenViewModel.swift
  Tangem/Modules/ManageTokens/ManageTokensCoordinator.swift
Labels: release, blocked

#3946 IOS-8068: Fix for search with only under market cap tokens
  Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
Labels: release

#3949 IOS-8072 Separate balances and pending balances filter
  Tangem/App/ViewModels/WalletModel/WalletModel+Balance.swift
  Tangem/Modules/StakingDetails/StakingDetailsViewModel.swift
  TangemStaking/Models/StakingBalance.swift
Labels: release

#3948 IOS-8060 [Staking] Show `temporaryUnavailable` as `network error`
  Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
Labels: release

#3968 IOS-8109 [Staking] Fix `Balance`
  Tangem/App/ViewModels/WalletModel/WalletModel+Balance.swift
  Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
  TangemStaking/Models/StakingBalance.swift
Labels: release

#3973 iOS-8119 [Staking] rename action param
  Tangem/App/Services/Analytics/Analytics+ParameterKey.swift
Labels: release

#3981 IOS-8100: Attempt to fix mini-charts loading crash
  Tangem/Modules/Markets/Providers/MarketsListChartsPreviewProvider.swift
Labels: release
